// Contenu du menu Tropical Resto-bar.
// Modifie librement ce fichier pour ajouter/retirer des plats ou changer les prix
// (prix en gourdes haïtiennes, "G").
const MENU = [
  {
    cat: "Entrées",
    items: [
      { name: "Crêpes salées", desc: "Choix de poulet ou jambon", price: 1000 },
      { name: "Acras", price: 500 },
      { name: "Acras de morue", price: 500 },
      { name: "Marinades Tropical", price: 400 },
      { name: "Fritay Tropical", desc: "Acras, plantains, marinades, chicken wings, pikliz et sauce", price: 2000, star: true },
      { name: "Boulettes de bœuf", price: 700 },
      { name: "Kibby", price: 600 },
    ],
  },
  {
    cat: "Burgers & Sandwichs",
    sub: "Chaque burger est servi avec des frites.",
    items: [
      { name: "Hamburger classique", price: 1000 },
      { name: "Cheeseburger", price: 1250 },
      { name: "Sandwich au griot", price: 1100 },
      { name: "Sandwich au poulet", desc: "Garni de salade, fromage, tomate, oignons et sauce tropicale", price: 1000 },
      { name: "Sandwich au jambon", desc: "Garni de salade, fromage, tomate, oignons et sauce tropicale", price: 1000 },
      { name: "Burger Tropical", desc: "Galette de bœuf, homard, fromage, tomates, oignons et accompagnements", price: 1500, star: true },
      { name: "Hot-dog et frites", price: 800 },
      { name: "Kibby et frites", price: 1000 },
    ],
  },
  {
    cat: "Viandes",
    sub: "Chaque plat est servi avec salade et deux accompagnements au choix.",
    items: [
      { name: "Cabri", desc: "Frit ou en sauce", price: 2250 },
      { name: "Bœuf", desc: "Frit ou en sauce", price: 1750 },
      { name: "Filet de bœuf", desc: "Sauce à la moutarde ou sauce au poivre", price: 1750 },
      { name: "Filet de bœuf au vin rouge", price: 2000 },
      { name: "Griot de porc", price: 1750 },
      { name: "Brochettes de bœuf", price: 1750 },
    ],
  },
  {
    cat: "Volailles",
    sub: "Chaque plat est servi avec salade et deux accompagnements au choix.",
    items: [
      { name: "Poulet", desc: "Frit ou en sauce", price: 1500 },
      { name: "Poulet barbecue", price: 1750 },
      { name: "Chicken wings Tropical", price: 1500, star: true },
      { name: "Poulet pays aux noix", price: 2250 },
      { name: "Dinde sautée aux légumes", price: 1750 },
      { name: "Pintade flambée au rhum", price: 2500 },
      { name: "Pintade en sauce", price: 2250 },
    ],
  },
  {
    cat: "Fruits de mer",
    sub: "Chaque plat est servi avec salade et deux accompagnements au choix parmi : frites, pommes de terre sautées, bananes pesées, riz blanc, riz collé aux pois.",
    items: [
      { name: "Poisson entier", desc: "En sauce ou frit — prix selon la taille", priceLabel: "2 500 – 4 000 G" },
      { name: "Poisson grillé", price: 2500 },
      { name: "Lambi en sauce", price: 2500 },
      { name: "Lambi Tropical", price: 2700 },
      { name: "Homard en sauce créole", price: 2500 },
      { name: "Homard grillé", price: 2750 },
      { name: "Crevettes panées", price: 2250 },
      { name: "Crevettes en sauce", desc: "Sauce rouge ou sauce au lait de coco", price: 2250 },
      { name: "Seafood boil", desc: "Selon disponibilité du marché", price: 4000, star: true },
    ],
  },
  {
    cat: "Pâtes",
    items: [
      { name: "Spaghetti bolognaise", price: 1250 },
      { name: "Spaghetti Tropical", desc: "Garni de poulet, légumes et sauce blanche", price: 1350 },
      { name: "Macaroni au poulet", price: 1000 },
      { name: "Macaroni du chef", desc: "Garni de porc, légumes et sauce au soja", price: 1250, star: true },
    ],
  },
  {
    cat: "Pizzas",
    items: [
      { name: "Végétarienne ou au fromage", price: 1700 },
      { name: "Haïti chérie", desc: "Sauce tomate, fromage, griot, oignons et piments doux", price: 2000, star: true },
      { name: "Au poulet barbecue", desc: "Sauce barbecue, fromage, poulet et oignons", price: 2000 },
      { name: "Hawaïenne au jambon", desc: "Sauce tomate, fromage, ananas, jambon et oignons", price: 2000 },
      { name: "Pepperoni", price: 1800 },
    ],
  },
  {
    cat: "Salades & Soupes",
    items: [
      { name: "Soupe au poulet", price: 800 },
      { name: "Soupe aux fruits de mer", price: 1250 },
      { name: "Salade Tropical", desc: "Laitue, tomates, bacon, oignons, crevettes et vinaigrette", price: 1500 },
      { name: "Salade au poulet", price: 1000 },
    ],
  },
  {
    cat: "Œufs & Petit-déjeuner",
    sub: "Chaque plat est servi avec une tasse de thé ou café.",
    items: [
      { name: "Omelette", desc: "Végétarienne ou jambon, servie avec du pain", price: 500 },
      { name: "Œufs sur plat", desc: "Servis avec du pain", price: 750 },
      { name: "Œufs brouillés", desc: "Servis avec du pain", price: 750 },
      { name: "Œufs créole au hareng", desc: "Servis avec du pain", price: 750 },
      { name: "Assiette Tropical", desc: "Œufs, pancakes et fruits frais", price: 1200, star: true },
      { name: "Crêpe nutella & bananes", price: 700 },
      { name: "Croissant jambon et fromage", price: 800 },
      { name: "Sandwich au jambon", price: 500 },
      { name: "Pain perdu", price: 700 },
      { name: "Pancakes du chef", price: 800 },
      { name: "Spaghetti", desc: "Aransò ou jambon", price: 750 },
      { name: "Sandwich aux œufs", price: 400 },
      { name: "Bananes + foie dur", price: 1000 },
      { name: "Bananes + œufs", price: 800 },
      { name: "Avoine", price: 600 },
      { name: "Plateau de fruits", price: 750 },
    ],
  },
  {
    cat: "Desserts",
    items: [
      { name: "Blanc-manger", price: 400 },
      { name: "Brownies", price: 300 },
      { name: "Gâteau renversé à l'ananas", price: 350, star: true },
      { name: "Crème glacée — 12 onces", price: 500 },
      { name: "Crème glacée — 16 onces", price: 750 },
      { name: "Crème glacée — coupe", price: 400 },
    ],
  },
  {
    cat: "Boissons",
    items: [
      { name: "Café glacé", price: 500 },
      { name: "Cappuccino", price: 500 },
      { name: "Chocolat chaud haïtien", price: 600 },
      { name: "Jus naturel", price: 400 },
      { name: "Smoothie", price: 700 },
      { name: "Milkshake / Frappuccino", price: 1000 },
    ],
  },
  {
    cat: "Les extras",
    items: [
      { name: "Pommes de terre frites", price: 500 },
      { name: "Pommes de terre sautées", price: 500 },
      { name: "Bananes pesées", price: 500 },
      { name: "Riz blanc", price: 500 },
      { name: "Riz collé aux pois", price: 500 },
      { name: "Légumes sautés", price: 500 },
    ],
  },
];
